config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :channels, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :subscriptions, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end

  get 'first-connection', to: "channels#first_connection"
  delete 'delete-selected-user/:id', to: "channels#delete_selected_user", as: "delete_selected_user"

  mount ActionCable.server => '/cable'
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :users, through: :subscriptions

  def one_to_one?
    subscriptions.size == 2
  end

  def init(selected_users, current_user)
    selected_users.each do |user|
      admin = one_to_one? || (user == current_user)
      Subscription.create(channel: self, user: user, admin: admin)
    end
  end

  def default_name(current_user)
    return name if name && !name.strip.empty?
    default_name = users.map(&:alias)
    default_name.delete(current_user.alias)
    default_name[0...2].join(", ")
  end
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :find_channel, only:        [:show, :edit, :update, :destroy]
  before_action :find_subscriptions, only:  [:show, :edit, :update]
  before_action :find_admin, only:          [:show, :edit, :update]
  before_action :find_users, only:          [:new,  :edit, :update]

  def show
    @subscription = Subscription.find_by(user: current_user, channel: @channel)
    @new_messages_limit = @subscription.new_messages_limit
    unless @channel.messages.empty?
      @subscription.update( last_message_id: @channel.messages.last.id)
    end
    @message = Message.new
    session[:user_ids] = [current_user.id]
    current_user.update(last_channel_id: @channel.id)

    # IMPORTANT. This is essential for the websocket authentification !!! :)
    cookies.signed[:user_id] = current_user.id
    cookies.signed[:channel_id] = params[:id]

    @iframely = Iframely::Requester.new api_key: ENV['IFRAMELY_KEY']  
  end

  def new
    @channel = Channel.new
    session[:user_ids] << select_params[:user_id] if params["selected_user"]
    @selected_users = User.selected_users(session[:user_ids])
  end

  def first_connection
    @first_subscription = Subscription.create(channel: Channel.first, user: current_user)
    @channel =  current_user.last_channel_id ? Channel.find(current_user.last_channel_id) : Channel.first
    redirect_to @channel
    # @first_subscription = Subscription.new(channel: Channel.first, user: current_user)
    # if @first_subscription.save
    #   @channel = Channel.create({name: ""})
    #   selected_users = User.selected_users([current_user.id, User.first.id])
    #   @channel.init(selected_users, current_user)
    #   redirect_to @channel
    # else
    #   redirect_to current_user.last_channel
    # end
  end

  def create
    @channel = Channel.new(channel_params)
    @selected_users = User.selected_users(session[:user_ids])
    if @selected_users.size > 1 && @channel.save
      @channel.init(@selected_users, current_user)
      redirect_to @channel
    else
      @users = current_user.friends
      render :new
    end
  end

  def edit
  end

  def update
    if @channel.update(channel_params)
      redirect_to edit_channel_path(@channel)
    else

      render :edit
    end
  end

  def destroy
    @channel.destroy
    redirect_to Channel.first
  end

  def delete_selected_user
    session[:user_ids].delete(params[:id])
    redirect_to new_channel_path
  end

  private

  def find_channel
    @channel = Channel.find(params[:id])
  end

  def find_subscriptions
    @subscriptions = !@channel.one_to_one? ? @channel.subscriptions : []
  end

  def find_admin
    @admin = @channel.subscriptions.find_by(user: current_user).admin
  end

  def find_users
    @users = params["search_user"] ? User.pgsearch(search_params[:name]) : current_user.friends
  end

  def search_params
    params.require(:search_user).permit(:name)
  end

  def select_params
    params.require(:selected_user).permit(:user_id)
  end

  def channel_params
    params.require(:channel).permit(:name)
  end

end

app/helpers/channel_helper.rb
module ChannelHelper
  def unread_channel_class(current_user, channel, sender_channel)
    if current_user.unread_messages_nbr(channel) == 0
      "id=unread-channel-#{channel.id}"
    elsif (channel == sender_channel) && (channel.messages.last == current_user.messages.last)
      ""
    else
      "class=unread"
    end
  end
end

app/views/channels/edit.html.erb
<h3><%= link_to @channel.default_name(current_user), @channel %></h3>
  <%= simple_form_for @channel do |f| %>
    <%= f.input :name, label: false, placeholder: @channel.name %>
    <%= f.submit "change the name" %>
  <% end %>
<% unless @channel.one_to_one? %>
  <ul>
    <% @subscriptions.each do |subscription| %>
      <% if !current_user?(subscription.user) %>
        <li>
          <%= subscription.user.alias %>
          <% if @admin && @subscriptions.size > 2 %>
            <!-- Button trigger modal -->
            <%= link_to "delete", [@channel, subscription], method: :delete, data: {confirm: "Are you sure! Do you want delete #{subscription.user}"} %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <h2>Add a new friend to channel</h2>

  <%= simple_form_for :search_user, url: edit_channel_path(@channel), method: :get do |f| %>
    <div>
      <%= f.input :name, label: false, placeholder: "ex : John Smith" %>
      <button type="submit" class="btn btn-default">
        <i class="fa fa-search"></i>
      </button>
    </div>
  <% end %>

  <div>
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= simple_form_for :selected_user, url: channel_subscriptions_path(@channel), method: :post do |f| %>
            <%= f.input :user_id, as: :hidden, input_html: {value: user.id } %>
            <%= f.submit user.alias %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= link_to "Delete the channel #{@channel.default_name(current_user)}", @channel, method: :delete, data: {confirm: "Are you sure! Do you want delete the channel #{@channel.default_name(current_user)}"}  %>


<!-- <a data-toggle="modal" href="/" data-target="#modal">Click me</a>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div> -->

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= simple_form_for @channel do |f| %>
  <%= f.input :name, label: false, placeholder: "Name of the channel" %>
  <div>
    <ul>
      <% @selected_users.each do |user| %>
        <% if !current_user?(user) %>
          <li>
            <%= user.alias %>
            <%= link_to "delete", delete_selected_user_path(user), method: :delete %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <%= f.submit %>
<% end %>

<h2>Add a new friend to channel</h2>

<%= simple_form_for :search_user, url: new_channel_path, method: :get do |f| %>
  <div>
    <%= f.input :name, label: false, placeholder: "ex : John Smith" %>
    <button type="submit" class="btn btn-default">
      <i class="fa fa-search"></i>
    </button>
  </div>
<% end %>

<div>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= simple_form_for :selected_user, url: new_channel_path, method: :get do |f| %>
          <%= f.input :user_id, as: :hidden, input_html: {value: user.id } %>
          <%= f.submit user.alias %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/channels/show.html.erb
<div class="hidden">
  <div id="current_user_id">
    <%= current_user.id %>
  </div>
</div>
<div class="wrapper-messenger">
  <div class="container-fluid">
    <div class="row">
      <%= render 'shared/channel-list' %>
      <%= render 'shared/messages-box' %>
    </div>
  </div>
</div>