config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :channels, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :subscriptions, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end

  get 'first-connection', to: "channels#first_connection"
  delete 'delete-selected-user/:id', to: "channels#delete_selected_user", as: "delete_selected_user"

  mount ActionCable.server => '/cable'
end

app/views/shared/_channel-list.html.erb
<div class="col-md-2" id="channel-list">
  <p><%= link_to "Create a new channel", new_channel_path %></p>
  <h3><%= @channel.default_name(current_user) %></h3>
  <% if @channel.one_to_one? || @admin %>
    <%= link_to "edit", edit_channel_path(@channel) %>
  <% end %>
  <ul>
    <% @subscriptions.each do |subscription| %>
      <% if !current_user?(subscription.user) %>
        <li><%= subscription.user.alias %></li>
      <% end %>
    <% end %>
  </ul>
  <ul>
    <% current_user.channels.each do |channel| %>
      <li>
        <% if current_user.messages.last == nil %>
          <% current_user.messages.last == 0 %>
        <% end %>
        <div <%= unread_channel_class(current_user, channel, @channel)%> >
          <%= link_to channel.default_name(current_user), channel %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_messages-box.html.erb
<div class="col-md-10" id="message-box">
  <ul id="messages-table">
    <% @channel.messages.each_with_index do |message, index| %>
      <% if index == @new_messages_limit %>
        New message <hr>
      <% end %>
      <li id="message-container">
        <div id="message-infos">
          <h1><%= message.user.alias %></h1>
          <p> | <%= message.updated_at.strftime("%d/%m/%y à %Hh%M")%></p>
        </div>
        <div class="content">
          <%= Rinku.auto_link(message.content, :all, 'target="_blank"').html_safe %>
        </div>
        <div class="iframe">
          <%= @iframely.get_oembed_json(message.first_url)["html"].html_safe if @iframely.get_oembed_json(message.first_url)["html"]  %>
        </div>
      </li>
      <div id="delete-btn">
        <% if current_user?(message.user) %>
            <%= link_to "delete", [@channel, message], method: :delete, data: {confirm: "Are you sure! Do you want delete this post"}  %>
        <% end %>
      </div>
    <% end %>
  </ul>
  <%= simple_form_for [@channel, @message], remote: true do |f| %>
    <%= f.input :content, label: false, id: "chat-text" %>
    <%= f.button :submit, 'Send', id:"submit-btn" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="hidden">
            <div id="current_user_id">
              <%= current_user.id %>
            </div>
          </div>
          <% if current_user.total_unread_messages_nbr %>
                <div class="badge badge-blue <%= 'hidden' if current_user.total_unread_messages_nbr == 0 %>" id="notification-<%= current_user.id %>">
                  <%= current_user.total_unread_messages_nbr %>
                </div>
          <% end %>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>